Repository voxpupuli/beaker-hostgenerator, pull requests merged in 2023-11, with the labels that each got.

#341 Add osx14-64 and osx14-ARM64 support
  lib/beaker-hostgenerator/data.rb
  lib/beaker-hostgenerator/hypervisor/abs.rb
  test/fixtures/generated/default/osx14-64aulcdfm
  test/fixtures/generated/default/osx14-ARM64a
  test/fixtures/generated/multiplatform/osx14-64aulcdfm-sles11-32-osx14-64a
  test/fixtures/generated/multiplatform/osx14-ARM64a-redhat9-POWER-osx14-ARM64aulcdfm
  test/fixtures/generated/multiplatform/redhat9-POWERa-osx14-ARM64-redhat9-POWERaulcdfm
  test/fixtures/generated/multiplatform/sles11-32a-osx14-64-sles11-32aulcdfm
  test/fixtures/generated/osinfo-version-0/osx14-64aulcdfm
  test/fixtures/generated/osinfo-version-0/osx14-ARM64a
  test/fixtures/generated/osinfo-version-1/osx14-64aulcdfm
  test/fixtures/generated/osinfo-version-1/osx14-ARM64a
Labels: enhancement

#342 2.8.0 release prep
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog

#343 explicitly install cronie on EL8+
  lib/beaker-hostgenerator/hypervisor/docker.rb
Labels: bug

#345 (PA-5948) Update host generator to use aarch64 for amazon linux
  lib/beaker-hostgenerator/data.rb
  lib/beaker-hostgenerator/hypervisor/abs.rb
  test/fixtures/generated/default/amazon2023-AARCH64aulcdfm
  test/fixtures/generated/multiplatform/amazon2023-AARCH64aulcdfm-solaris114-64-amazon2023-AARCH64a
  test/fixtures/generated/multiplatform/solaris114-64f-amazon2023-AARCH64-solaris114-64l
  test/fixtures/generated/osinfo-version-0/amazon2023-AARCH64aulcdfm
  test/fixtures/generated/osinfo-version-1/amazon2023-AARCH64aulcdfm
Labels: bug

#346 Release 2.8.2
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog

#348 readme fixes
  README.md
Labels: docs

#347 Add Fedora 39 support
  lib/beaker-hostgenerator/data.rb
  spec/helpers.rb
Labels: enhancement
