Repository voxpupuli/beaker-hostgenerator, pull requests merged in 2024-06, with the labels that each got.

#371 Don't prepend amd64/ for opensuse images
  lib/beaker-hostgenerator/hypervisor/docker.rb
  test/fixtures/per-host-settings/docker-regex-validation.yaml
Labels: bug

#372 Add Amazon 2
  lib/beaker-hostgenerator/data.rb
  test/fixtures/generated/default/amazon2-AARCH64f
  test/fixtures/generated/default/amazon2-AARCH64m
  test/fixtures/generated/multiplatform/amazon2-AARCH64f-solaris11-64-amazon2-AARCH64l
  test/fixtures/generated/multiplatform/amazon2-AARCH64m-solaris11-32-amazon2-AARCH64u
  test/fixtures/generated/multiplatform/solaris11-32l-amazon2-AARCH64-solaris11-32f
  test/fixtures/generated/multiplatform/solaris11-64d-amazon2-AARCH64-solaris11-64c
  test/fixtures/generated/osinfo-version-0/amazon2-AARCH64f
  test/fixtures/generated/osinfo-version-0/amazon2-AARCH64m
  test/fixtures/generated/osinfo-version-1/amazon2-AARCH64f
  test/fixtures/generated/osinfo-version-1/amazon2-AARCH64m
Labels: enhancement

#376 Add Almalinux9 AARCH64 and Rocky9 AARCH64
  lib/beaker-hostgenerator/data.rb
  test/fixtures/generated/default/almalinux9-AARCH64d
  test/fixtures/generated/default/rocky9-AARCH64a
  test/fixtures/generated/multiplatform/almalinux9-AARCH64d-sles12-S390X-almalinux9-AARCH64c
  test/fixtures/generated/multiplatform/rocky9-AARCH64a-sles11-32-rocky9-AARCH64aulcdfm
  test/fixtures/generated/multiplatform/sles11-32d-rocky9-AARCH64-sles11-32c
  test/fixtures/generated/multiplatform/sles12-S390Xa-almalinux9-AARCH64-sles12-S390Xaulcdfm
  test/fixtures/generated/osinfo-version-0/almalinux9-AARCH64d
  test/fixtures/generated/osinfo-version-0/rocky9-AARCH64a
  test/fixtures/generated/osinfo-version-1/almalinux9-AARCH64d
  test/fixtures/generated/osinfo-version-1/rocky9-AARCH64a
Labels: enhancement

#377 Release 2.14.0
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog

#374 Use latest CentOS boxes instead of specific dates
  lib/beaker-hostgenerator/data.rb
  test/fixtures/per-host-settings/vagrant-hypervisor.yaml
Labels: bug

#379 Release 2.14.1
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog
