Repository voxpupuli/beaker-hostgenerator, pull requests merged in 2024-05, with the labels that each got.

#364 Add beaker-hostgenerator support for Windows 2016 FIPS
  lib/beaker-hostgenerator/data.rb
  test/fixtures/generated/default/windowsfips2016-6432c
  test/fixtures/generated/multiplatform/fedora28-32c-windowsfips2016-6432-fedora28-32d
  test/fixtures/generated/multiplatform/windowsfips2016-6432c-fedora28-32-windowsfips2016-6432d
  test/fixtures/generated/osinfo-version-0/windowsfips2016-6432c
  test/fixtures/generated/osinfo-version-1/windowsfips2016-6432c
Labels: enhancement

#366 Release 2.12.0
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog

#367 Update Amazon Linux 2 bindings
  lib/beaker-hostgenerator/data.rb
Labels: bug

#368 Release 2.12.1
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog

#369 Use Red Hat 7 for Amazon Linux 2 x86_64
  lib/beaker-hostgenerator/data.rb
Labels: bug
