Repository voxpupuli/beaker-hostgenerator, pull requests merged in 2025-08, with the labels that each got.

#416 Require Ruby 3.2 or newer
  .rubocop.yml
  .rubocop_todo.yml
  Rakefile
  beaker-hostgenerator.gemspec
  bin/beaker-hostgenerator
  lib/beaker-hostgenerator/parser.rb
  spec/beaker-hostgenerator/generator_spec.rb
  spec/beaker-hostgenerator/parser_spec.rb
Labels: backwards-incompatible

#322 Drop legacy EL6 data
  lib/beaker-hostgenerator/data.rb
  test/fixtures/generated/default/oracle6-32d
  test/fixtures/generated/default/oracle6-64f
  test/fixtures/generated/default/redhat6-32aulcdfm
  test/fixtures/generated/default/redhat6-64a
  test/fixtures/generated/multiplatform/amazon7-64a-redhat9-POWER-amazon7-64aulcdfm
  test/fixtures/generated/multiplatform/oracle6-32d-solaris11-SPARC-oracle6-32c
  test/fixtures/generated/multiplatform/oracle6-64f-solaris11-64-oracle6-64l
  test/fixtures/generated/multiplatform/redhat6-32aulcdfm-sles11-32-redhat6-32a
  test/fixtures/generated/multiplatform/redhat6-64a-redhat8-AARCH64-redhat6-64aulcdfm
  test/fixtures/generated/multiplatform/redhat6-64m-sles15-64-redhat6-64u
  test/fixtures/generated/multiplatform/redhat8-AARCH64a-redhat6-64-redhat8-AARCH64aulcdfm
  test/fixtures/generated/multiplatform/redhat9-POWERf-amazon7-64-redhat9-POWERl
  test/fixtures/generated/multiplatform/sles11-32d-redhat6-32-sles11-32c
  test/fixtures/generated/multiplatform/sles15-64l-redhat6-64-sles15-64f
  test/fixtures/generated/multiplatform/solaris11-64m-oracle6-64-solaris11-64u
  test/fixtures/generated/multiplatform/solaris11-SPARCaulcdfm-oracle6-32-solaris11-SPARCa
  test/fixtures/generated/osinfo-version-0/oracle6-32d
  test/fixtures/generated/osinfo-version-0/oracle6-64f
  test/fixtures/generated/osinfo-version-0/redhat6-32aulcdfm
  test/fixtures/generated/osinfo-version-0/redhat6-64a
  test/fixtures/generated/osinfo-version-1/oracle6-32d
  test/fixtures/generated/osinfo-version-1/oracle6-64f
  test/fixtures/generated/osinfo-version-1/redhat6-32aulcdfm
  test/fixtures/generated/osinfo-version-1/redhat6-64a
Labels: backwards-incompatible

#417 Release 3.0.0
  .github/workflows/release.yml
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog

#420 CI: configure minimal github token permissions
  .github/workflows/test.yml
  Gemfile
Labels: skip-changelog

#422 Add Debian 13 support and make CentOS & Debian easier to maintain
  lib/beaker-hostgenerator/data.rb
  lib/beaker-hostgenerator/hypervisor/vagrant.rb
Labels: enhancement

#427 Release 3.2.0
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog

#428 Use non library path for rocky 10
  lib/beaker-hostgenerator/hypervisor/docker.rb
Labels: bug

#429 Release 3.2.1
  CHANGELOG.md
  lib/beaker-hostgenerator/version.rb
Labels: skip-changelog
